### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by Demonslyr** [nshaheed/eecs448_semesterProj#2]
My understanding is we're using a mix of keyboard and mouse control.
The controls so far are as follows:
W = move ship up
S = move ship down
A = move ship left
D = move ship right
Space = Unknown
Escape = quit game (soon to be pause/unpause if game is running and quit if in menu)

**Comment by nshaheed** [comment]
For the player's weapon is it going to be a constant stream of projectiles or will it be dependent on the player pressing a button?  The controls you've listed sound good to me.

**Comment by Demonslyr** [comment]
I was thinking that shooting could be holding the space bar (which would result in only firing forward from the player or shooting could be holding the left mouse button and the projectiles would aimed with the mouse pointer. In both cases the projectiles would be a constant stream toggled by key(mouse) press/release and neither would be difficult to write.

Edit: A little in favor of the first now that I run it through my head more.

**Comment by nshaheed** [comment]
Sounds good to me.
