### ISSUE TITLE
stuff still to do game wise

### ISSUE THREAD

**Issue by Demonslyr** [nshaheed/eecs448_semesterProj#3]
remaining things to implement
enemy spawning-Dan(no one seems to be tanking it)
enemy drawing -Dan(no one seems to be tanking it)
enemy ai-Dan(no one seems to be tanking it)
enemy projectile spawning
~~threading each independent (i can handle this-Dan)
~~score and hp text displaying~~ (still need means to update points -Nick)
migrating menu to a class (I've moved both the pause and main menus to functions, it would probably be ideal to move them to a separate file though -Nick)
migrating sound to a class
migrate all the initialization in main into an init script or function idk
projectile sounds
damage sounds
~~pause menu~~ -Nick

boss enemy?
how to play screen?
credits?
player damage upgrade?
powerups?

**Comment by nshaheed** [comment]
Question, since the classes you've created for projectile/player aren't really following the outlines I've set up in class_outlines.txt, is it worth continuing to work on tests/outlines for things?  I was also working on a projectile class that I was making with the outline in mind.

**Comment by Demonslyr** [comment]
player and enemy classes will inherit from a ship class. I need to write it still. I added the other get/set methods to player, otherwise I think the only thing the player class is missing is the "weapon" method since the players projectiles will be triggered by, right now, the space bar being pressed. I pulled it out into the control for the time being. The number of arguments passed into the projectile class is not final, several are redundant and I'll pull them out. I guess I missed your projectile class in class outlines, reading through it now to see how I can restructure the proj_holder and proj_obj classes to include weapon.

**Comment by Demonslyr** [comment]
If you already have a projectile handling solution based on your weapon and projectile class, I can just add the weapon attribute to the ship class and let you take it from there if that would just work better. I put the projectile solution together in about 30 minutes so I'm not really attached to it.

**Comment by Demonslyr** [comment]
Also, on your comment about casting doubles to ints in the movement pattern method for projectiles. I think we should store the (x,y) positions and velocities as doubles and convert the (x,y) positions to ints right before being passed to the blit function.

**Comment by nshaheed** [comment]
Did everything but sound
