### ISSUE TITLE
Player shots not reset on game restart

### ISSUE THREAD

**Issue by ballesta25** [nshaheed/eecs448_semesterProj#9]
Player shots that are in the air when the game stops will re-appear when the game is re-started.  This can happen when the player dies, or when you pause the game and re-start.  
To reproduce: 
1. start a game
2. shoot
3. pause while shots are in the air
4. return to menu
5. start a new game

The shots will continue from their previous positions.

**Comment by Demonslyr** [comment]
When the 'a' key and left arrow are pressed simultaneously, the ship will move at twice the velocity
